
apiVersion: v1
metadata:
  name: 'hub'
baseDomain: sandbox1472.opentlc.com
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      rootVolume:
        iops: 4000
        size: 300
        type: io1
      type: m5.4xlarge
compute:
- hyperthreading: Enabled
  name: 'worker'
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 300
        type: io1
      type: m5.4xlarge
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.127.0.0/16
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.7.0.0/16
  serviceNetwork:
  - 172.27.0.0/16
platform:
  aws:
    region: us-east-1
sshKey: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOEcqmhJj5sBGHZgDpgzWkog3O0KDFLr34MeISmoIN40ugPNFqlT9dwtWI7bhKA502erCLXKQBpAw5Levtq6QW25alHTVAzq4O9O2TlfwcuN7aSjrZlezBoGtcDEu+gL2aNmRqV8b3Ujm5Jo6hkIijo4y+fA9vwoo5owTH+ms5y29J1OM8voLTiY9evYR/OinuMdK1UcpNHDru4YR+EzxQk3Mlf8HCvwNOhv0NHoNPoQfzDsGQitdNkcJq+E4WkpPInnvrsavhb8bNsD9vN8o/bWAZb03gpIWyxUdwrBLmnl+lZuukUyTG0VlL4xl3+yYKC42pJL7nXbk2rEsLbIbz cmarango@cmarango-mac
